---
version: "2.0"

services:
  catecoin-scanner:
    image: ghcr.io/toxmon/catecoin-scanner:sha-ebd9f8e
    env:
      - TELEGRAM_BOT_TOKEN=8978112955:AAGeQYeosjbKiMykv1YVBAPHyVqeowi9vC0
      - TELEGRAM_CHAT_ID=6748258274
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    catecoin-scanner:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    akash:
      pricing:
        catecoin-scanner:
          denom: uact
          amount: 1000

deployment:
  catecoin-scanner:
    akash:
      profile: catecoin-scanner
      count: 1
